### ISSUE TITLE
👀

### ISSUE THREAD

**Issue by pakoito** [xenomachina/kessel#1]
![](http://www.reactiongifs.com/r/watching.gif)

**Comment by pakoito** [comment]
Cool project :D Are you up for a chat? I'm putting together a talk about the Arrow ecosystem!

**Comment by xenomachina** [comment]
Sure! How would you like to chat?

**Comment by pakoito** [comment]
Gitter? https://gitter.im/arrow-kt/Lobby I'm also in kotlinlang slack!
